name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_WRITE_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
        # Configure git credential helper for Hugging Face
        git config --global credential.helper store
        echo "https://${HF_TOKEN}@git.hf.co" > ~/.git-credentials
        
        git clone https://git.hf.co/spaces/daniela-veloz/WebSummarizer hf-space
        cd hf-space
        
        # Sync files using rsync, excluding .git directory
        rsync -av --exclude='.git' ../. .
        
        # Commit and push changes
        git add .
        git commit -m "Sync from GitHub repo" || exit 0
        git push origin main